apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
    version: v1
  name: hello-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      version: v1
  template:
    metadata:
      labels:
        app: hello
        version: v1
    spec:
      containers:
      - image: registry.ocp.zyl.io:5000/hello:v1
        imagePullPolicy: Always
        name: hello
