apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
    version: v1
  name: hello-v1
  namespace: 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      version: v1
  template:
    metadata:
      labels:
        app: hello
        version: v1
    spec:
      containers:
      - image: core.apps.ocp.zyl.io/hello/hello:v1-metrics
        imagePullPolicy: Always
        name: hello
