apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
    service: hello
  name: hello
spec:
  ports:
  - name: http
    port: 9080
    targetPort: web
    protocol: TCP
  selector:
    app: hello
  sessionAffinity: None
  type: ClusterIP
