apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: greeter
    version: v4.0
    protos: grpc
  name: greeter-v4-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
      version: v4.0
      protos: grpc
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "True"
      labels:
        app: greeter
        version: v4.0
        protos: grpc
    spec:
      containers:
      - image: core.apps.ocp.zyl.io/hello/greeter:v4.0
        imagePullPolicy: Always
        name: greeter
        ports:
        - name: web
          containerPort: 9080
          protocol: TCP
        env:
        - name: MESSAGE
          value: 'Grpc V4.0 Hello'
        - name: JAEGER_ONE_SPAN_PER_RPC
          value: 'False'
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent:1.17.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5775
            name: zk-compact-trft
            protocol: UDP
          - containerPort: 5778
            name: config-rest
            protocol: TCP
          - containerPort: 6831
            name: jg-compact-trft
            protocol: UDP
          - containerPort: 6832
            name: jg-binary-trft
            protocol: UDP
          - containerPort: 14271
            name: admin-http
            protocol: TCP
        args:
          - --reporter.grpc.host-port=dns:///jaeger-collector-headless.istio-system:14250
          - --reporter.type=grpc
          - --log-level=debug
