apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
    version: v3.0
  name: hello-v3.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      version: v3.0
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "True"
      labels:
        app: hello
        version: v3.0
    spec:
      containers:
      - image: core.apps.ocp.zyl.io/hello/hello:v3.0
        imagePullPolicy: Always
        name: hello
        ports:
        - name: web
          containerPort: 9080
          protocol: TCP
        env:
        - name: PUBLISHER
          value: 'http://publisher:9080'
        - name: GREETER
          value: 'http://greeter:9080'
