apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
    version: v4.0
  name: hello-v4-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      version: v4.0
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "True"
      labels:
        app: hello
        version: v4.0
    spec:
      containers:
      - image: core.apps.ocp.zyl.io/hello/hello:v4.0
        imagePullPolicy: Always
        name: hello
        ports:
        - name: web
          containerPort: 9080
          protocol: TCP
        env:
        - name: PUBLISHER
          value: 'http://publisher:9080'
        - name: GREETER
          value: 'greeter-grpc.hello.svc.cluster.local:9080'
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent:1.17.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5775
            name: zk-compact-trft
            protocol: UDP
          - containerPort: 5778
            name: config-rest
            protocol: TCP
          - containerPort: 6831
            name: jg-compact-trft
            protocol: UDP
          - containerPort: 6832
            name: jg-binary-trft
            protocol: UDP
          - containerPort: 14271
            name: admin-http
            protocol: TCP
        args:
          - --reporter.grpc.host-port=dns:///jaeger-collector-headless.istio-system:14250
          - --reporter.type=grpc
          - --log-level=debug
