apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: publisher
spec:
  host: publisher
  subsets:
  - name: v3-1
    labels:
      version: v3.1
  - name: v3-2
    labels:
      version: v3.2
  - name: v4-0
    labels:
      version: v4.0
