apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: greeter
spec:
  host: greeter
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v3-0-1
    labels:
      version: v3.0-1
  - name: v3-0-2
    labels:
      version: v3.0-2
    trafficPolicy:
      loadBalancer:
        simple: RANDOM
  - name: v3-0-3
    labels:
      version: v3.0-3
    trafficPolicy:
      loadBalancer:
        simple: LEAST_CONN
