apiVersion: v1
kind: Service
metadata:
  labels:
    app: greeter
    protos: grpc
  name: greeter-grpc
spec:
  ports:
  - name: http
    port: 9080
    targetPort: 9080
    protocol: TCP
  selector:
    app: greeter
    protos: grpc
  sessionAffinity: None
  type: ClusterIP
