apiVersion: v1
kind: Service
metadata:
  labels:
    app: publisher
    service: publisher
  name: publisher
spec:
  ports:
  - name: http
    port: 9080
    targetPort: web
    protocol: TCP
  selector:
    app: publisher
  sessionAffinity: None
  type: ClusterIP
